### ISSUE TITLE
Graphe des précipitations ?

### ISSUE THREAD

**Issue by ybabel** [GaelGRIFFON/previsionpluie#1]
Bonjour,
le plugin marche bien jusque la !! 
Pour ma part, j'aurais besoin de pouvoir historiciser les probabilités de pluies, pour avoir un graphe à l'année des précipitations, du moins, quelque chose de plus approchant possible.
Ce serait possible de rajouter le fameux index de probabilité qui > 12 veut dire "pluie" dans l'affichage du widget ?

https://www.jeedom.fr/forum/viewtopic.php?f=28&t=8265&p=189525#p189525

**Comment by GaelGRIFFON** [comment]
Je viens de mettre à dispo sur le market avec la V1! ;)

**Comment by ybabel** [comment]
rapide ! merci
